{% set name = "txrm2tiff" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DiamondLightSource/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0643ED18AC37F4BDD85B95291BA5F3F27B22687BF7DEC4867DD625B04B4289A7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - {{ name }} = {{ name }}.scripts.commandline:main
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.17.4
    - scipy
    - tifffile >=2020.11.26
    - omexml-dls >=1.0.3
    - olefile >=0.46
    - pillow >=5.3
    - pywin32  # [win]

test:
  imports:
    - {{ name }}
    - win32com.client  # [win]
  source_files:
    - tests
  requires:
    - parameterized
  commands:
    - python -m unittest discover tests -p "test_*.py" -vv

about:
  home: https://github.com/DiamondLightSource/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Converts txrm/xrm files to OME tif/tiff files

  description: |
    Converts txrm/xrm files to OME tif/tiff files.
    txrm2tiff was created for users of beamline B24 of Diamond Light 
    Source by Thomas Fish. This has been adapted from B24's the automatic 
    processing pipeline. Parts of this code were originally written by 
    Kevin Savage, with further additions and amendments by Peter Chang, 
    Victoria Beilsten-Edmands, and Thomas Fish.
  doc_url: https://github.com/DiamondLightSource/{{ name }}/blob/master/README.md
  dev_url: https://github.com/DiamondLightSource/{{ name }}

extra:
  recipe-maintainers:
    - thomasmfish
